//! Deterministic test harness for the public commissioner API.
//!
//! The production commissioner lazily establishes DTLS and then exchanges
//! encrypted MeshCoP CoAP messages with a border agent. Most public API tests do
//! not need a real UDP socket, EC J-PAKE handshake, or record-protection state;
//! they need deterministic control over the request/response conversation after
//! DTLS has delivered application data.
//!
//! This harness scripts that post-DTLS MeshCoP layer. Each public API call still
//! builds a real [`crate::meshcop::CoapMessage`], advances commissioner state,
//! and runs the production incoming-message loop (token correlation, empty-ACK
//! skipping, UDP_RX decapsulation, and notification routing) over the scripted
//! message stream. Crypto and wire-level DTLS behavior remain covered by the
//! dedicated `dtls` and `crypto` tests.

use std::collections::VecDeque;
use std::net::Ipv6Addr;

use crate::{
    Result,
    error::Error,
    meshcop::{
        self, CoapCode, CoapMessage, CoapType, CommissionerOperation, MeshcopState,
        TLV_COMMISSIONER_SESSION_ID, TLV_STATE,
    },
};

/// One observed request sent by a public commissioner method.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ObservedRequest {
    /// Logical operation selected by the public API method.
    pub operation: CommissionerOperation,
    /// Decoded CoAP request generated by the production request builder.
    ///
    /// For proxied operations this is the outer UDP_TX.ntf message; the inner
    /// request can be recovered with [`crate::meshcop::parse_udp_rx`]-style
    /// decapsulation via [`ObservedRequest::inner_message`].
    pub message: CoapMessage,
}

impl ObservedRequest {
    /// Returns the proxied inner request when `message` is a UDP_TX.ntf.
    pub(crate) fn inner_message(&self) -> Option<CoapMessage> {
        let tlvs = crate::tlv::TlvSet::parse(&self.message.payload).ok()?;
        let encapsulation = tlvs.last_value(meshcop::TLV_UDP_ENCAPSULATION)?;
        CoapMessage::decode(encapsulation.get(4..)?).ok()
    }

    /// Returns the UDP_TX destination address when `message` is a UDP_TX.ntf.
    pub(crate) fn proxy_destination(&self) -> Option<Ipv6Addr> {
        let tlvs = crate::tlv::TlvSet::parse(&self.message.payload).ok()?;
        let address = tlvs.last_value(meshcop::TLV_IPV6_ADDRESS)?;
        let octets: [u8; 16] = address.try_into().ok()?;
        Some(Ipv6Addr::from(octets))
    }
}

/// A scripted MeshCoP exchange expected by the harness.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ScriptedExchange {
    operation: CommissionerOperation,
    responses: Vec<ScriptedResponse>,
}

impl ScriptedExchange {
    /// Expects `operation` and delivers `responses` as the incoming stream.
    ///
    /// Empty ACK responses are consumed by the same loop the live path uses and
    /// therefore do not complete the public API call.
    pub(crate) fn new(
        operation: CommissionerOperation,
        responses: impl IntoIterator<Item = ScriptedResponse>,
    ) -> Self {
        Self {
            operation,
            responses: responses.into_iter().collect(),
        }
    }
}

/// Response template used by a scripted exchange.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ScriptedResponse {
    /// An empty ACK matching the request message ID.
    EmptyAck,
    /// A CoAP Changed response with the supplied MeshCoP payload.
    Changed {
        /// Response payload.
        payload: Vec<u8>,
        /// Whether the response should be confirmable.
        confirmable: bool,
    },
    /// A CoAP Content response with the supplied payload.
    Content {
        /// Response payload.
        payload: Vec<u8>,
        /// Whether the response should be confirmable.
        confirmable: bool,
    },
    /// A response with an arbitrary CoAP code (token/message-ID echoed from the
    /// request), for negative tests such as error-coded responses.
    Coded {
        /// Response code.
        code: CoapCode,
        /// Response payload.
        payload: Vec<u8>,
    },
    /// A raw message for negative tests, such as token mismatches.
    Raw(CoapMessage),
    /// A response wrapped in a UDP_RX.ntf encapsulation.
    ///
    /// The inner template is rendered against the request encapsulated in the
    /// observed UDP_TX.ntf so tokens and message IDs mirror the proxied
    /// request, exactly like a Thread device answering through the border
    /// agent proxy.
    UdpRx {
        /// Source address reported by the UDP_RX encapsulation.
        source_address: Ipv6Addr,
        /// Source port reported by the UDP_RX encapsulation.
        source_port: u16,
        /// Destination port reported by the UDP_RX encapsulation.
        destination_port: u16,
        /// Inner response template.
        inner: Box<ScriptedResponse>,
    },
}

impl ScriptedResponse {
    /// Creates an empty ACK response.
    pub(crate) const fn empty_ack() -> Self {
        Self::EmptyAck
    }

    /// Creates an accepting Changed response.
    pub(crate) fn accept() -> Self {
        Self::changed(state_payload(MeshcopState::Accept), false)
    }

    /// Creates a rejecting Changed response.
    pub(crate) fn reject() -> Self {
        Self::changed(state_payload(MeshcopState::Reject), false)
    }

    /// Creates a pending Changed response.
    pub(crate) fn pending() -> Self {
        Self::changed(state_payload(MeshcopState::Pending), false)
    }

    /// Creates an accepting petition response with a commissioner session ID.
    pub(crate) fn petition_accept(session_id: u16) -> Self {
        let mut payload = state_payload(MeshcopState::Accept);
        append_u16(&mut payload, TLV_COMMISSIONER_SESSION_ID, session_id);
        Self::changed(payload, false)
    }

    /// Creates a rejecting petition response with an existing commissioner ID.
    pub(crate) fn petition_reject(existing_commissioner_id: &str) -> Self {
        let mut payload = state_payload(MeshcopState::Reject);
        append_tlv(
            &mut payload,
            crate::meshcop::TLV_COMMISSIONER_ID,
            existing_commissioner_id.as_bytes(),
        );
        Self::changed(payload, false)
    }

    /// Creates a Changed response without a State TLV.
    pub(crate) fn changed_without_state() -> Self {
        Self::changed(Vec::new(), false)
    }

    /// Creates a non-confirmable Changed response with `payload`.
    pub(crate) fn changed(payload: Vec<u8>, confirmable: bool) -> Self {
        Self::Changed {
            payload,
            confirmable,
        }
    }

    /// Creates a non-confirmable Content response with `payload`.
    pub(crate) fn content(payload: Vec<u8>) -> Self {
        Self::Content {
            payload,
            confirmable: false,
        }
    }

    /// Wraps `inner` in a UDP_RX encapsulation from `source_address`.
    pub(crate) fn proxied(source_address: Ipv6Addr, inner: ScriptedResponse) -> Self {
        Self::UdpRx {
            source_address,
            source_port: meshcop::DEFAULT_MM_PORT,
            destination_port: meshcop::DEFAULT_MM_PORT,
            inner: Box::new(inner),
        }
    }

    /// Renders this template against the logical (decapsulated) request so
    /// response tokens and message IDs mirror what a Thread device would echo.
    fn into_message(self, logical_request: &CoapMessage) -> Result<CoapMessage> {
        Ok(match self {
            Self::EmptyAck => CoapMessage::empty_ack(logical_request.message_id),
            Self::Changed {
                payload,
                confirmable,
            } => response(logical_request, CoapCode::CHANGED, payload, confirmable),
            Self::Content {
                payload,
                confirmable,
            } => response(logical_request, CoapCode::CONTENT, payload, confirmable),
            Self::Coded { code, payload } => response(logical_request, code, payload, false),
            Self::Raw(message) => message,
            Self::UdpRx {
                source_address,
                source_port,
                destination_port,
                inner,
            } => {
                let inner_message = inner.into_message(logical_request)?;
                udp_rx_message(
                    source_address,
                    source_port,
                    destination_port,
                    &inner_message.encode()?,
                )?
            }
        })
    }
}

/// Extracts the inner request from an observed UDP_TX.ntf message.
///
/// Falls back to the outer message for direct exchanges so raw and
/// notification templates can be scripted on any route.
fn decapsulated_request(request: &CoapMessage) -> Result<CoapMessage> {
    let tlvs = crate::tlv::TlvSet::parse(&request.payload)?;
    match tlvs.last_value(meshcop::TLV_UDP_ENCAPSULATION) {
        Some(encapsulation) if encapsulation.len() >= 4 => CoapMessage::decode(&encapsulation[4..]),
        _ => Ok(request.clone()),
    }
}

/// Builds a UDP_RX.ntf message carrying `inner` bytes.
pub(crate) fn udp_rx_message(
    source_address: Ipv6Addr,
    source_port: u16,
    destination_port: u16,
    inner: &[u8],
) -> Result<CoapMessage> {
    let mut encapsulation = Vec::with_capacity(4 + inner.len());
    encapsulation.extend_from_slice(&source_port.to_be_bytes());
    encapsulation.extend_from_slice(&destination_port.to_be_bytes());
    encapsulation.extend_from_slice(inner);

    let mut payload = Vec::new();
    append_tlv(
        &mut payload,
        meshcop::TLV_IPV6_ADDRESS,
        &source_address.octets(),
    );
    append_tlv(&mut payload, meshcop::TLV_UDP_ENCAPSULATION, &encapsulation);
    CoapMessage::post_request(
        CoapType::NonConfirmable,
        0x7a7a,
        Vec::new(),
        meshcop::uri::UDP_RX,
        payload,
    )
}

/// Scripted post-DTLS MeshCoP transport.
#[derive(Debug, Default)]
pub(crate) struct ScriptedMeshcopTransport {
    exchanges: VecDeque<ScriptedExchange>,
    observed_requests: Vec<ObservedRequest>,
    sent_messages: Vec<CoapMessage>,
}

impl ScriptedMeshcopTransport {
    /// Creates a transport from the ordered exchange script.
    pub(crate) fn new(exchanges: impl IntoIterator<Item = ScriptedExchange>) -> Self {
        Self {
            exchanges: exchanges.into_iter().collect(),
            observed_requests: Vec::new(),
            sent_messages: Vec::new(),
        }
    }

    /// Returns requests observed so far.
    pub(crate) fn observed_requests(&self) -> &[ObservedRequest] {
        &self.observed_requests
    }

    /// Returns every message the client sent outside of exchanges, such as
    /// ACKs for confirmable responses and proxied acknowledgements.
    pub(crate) fn sent_messages(&self) -> &[CoapMessage] {
        &self.sent_messages
    }

    /// Returns confirmable response message IDs for which the client generated
    /// an empty ACK.
    pub(crate) fn acked_confirmable_responses(&self) -> Vec<u16> {
        self.sent_messages
            .iter()
            .filter(|message| {
                message.ty == CoapType::Acknowledgement && message.code == CoapCode::EMPTY
            })
            .map(|message| message.message_id)
            .collect()
    }

    /// Returns the number of exchanges not yet consumed.
    pub(crate) fn remaining_exchange_count(&self) -> usize {
        self.exchanges.len()
    }

    /// Records a non-exchange message sent by the client.
    pub(crate) fn record_sent(&mut self, message: CoapMessage) {
        self.sent_messages.push(message);
    }

    /// Consumes the next scripted exchange and returns its incoming stream.
    pub(crate) fn exchange(
        &mut self,
        operation: CommissionerOperation,
        request: CoapMessage,
    ) -> Result<VecDeque<CoapMessage>> {
        let exchange = self
            .exchanges
            .pop_front()
            .ok_or(Error::InvalidState("scripted MeshCoP exchange missing"))?;
        if exchange.operation != operation {
            return Err(Error::InvalidState("scripted MeshCoP operation mismatch"));
        }

        let encoded = request.encode()?;
        let request = CoapMessage::decode(&encoded)?;
        self.observed_requests.push(ObservedRequest {
            operation,
            message: request.clone(),
        });

        let logical_request = decapsulated_request(&request)?;
        let mut incoming = VecDeque::new();
        for template in exchange.responses {
            let message = template.into_message(&logical_request)?;
            // Round-trip through the wire form so the client sees exactly what
            // a live border agent would deliver.
            incoming.push_back(CoapMessage::decode(&message.encode()?)?);
        }
        Ok(incoming)
    }
}

fn response(
    request: &CoapMessage,
    code: CoapCode,
    payload: Vec<u8>,
    confirmable: bool,
) -> CoapMessage {
    CoapMessage {
        ty: if confirmable {
            CoapType::Confirmable
        } else {
            CoapType::Acknowledgement
        },
        code,
        message_id: request.message_id,
        token: request.token.clone(),
        options: Vec::new(),
        payload,
    }
}

fn state_payload(state: MeshcopState) -> Vec<u8> {
    let mut payload = Vec::new();
    append_tlv(&mut payload, TLV_STATE, &[state.to_wire()]);
    payload
}

fn append_u16(out: &mut Vec<u8>, ty: u8, value: u16) {
    append_tlv(out, ty, &value.to_be_bytes());
}

fn append_tlv(out: &mut Vec<u8>, ty: u8, value: &[u8]) {
    out.push(ty);
    out.push(value.len() as u8);
    out.extend_from_slice(value);
}
